version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: ts-morph
    versions:
    - 10.0.0
    - 10.0.1
    - 9.1.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
